### ISSUE TITLE
Next steps - installing and running R Hector

### ISSUE THREAD

**Issue by bpbond** [NatanelHa/Ha-Hector-Internship#1]
Hi Natanel, good discussion yesterday, thanks. Here are my suggestions ( @dawnlwoodard please edit as you see fit) for next steps:

1.	You’ve read about the Hector model, and are reading more this week. Let’s dive in!
2.	The Hector manual is here: https://jgcri.github.io/hector/articles/manual/. Follow the instructions in the first part of the page on installing and building Hector to install its R package (don’t clone the Hector repository yet, just use `devtools::install_github()` to install it).
3.	Follow the instructions in the first vignette on using R Hector: https://jgcri.github.io/hector/articles/intro-to-hector.html. In particular, do the first part (“Basic run”) and reproduce the output, the look through (and hopefully do) the second section (“Setting parameters”).
4.	Your reading for this week is given in the google sheet, as usual.

Questions? Please let us know!

**Comment by NatanelHa** [comment]
I was able to successfully download and run Hector on my computer. I was also able to go through the entirety of the first vignette entitled "A tour of the Hector R interface".  At this moment I don't have any questions, because I was able to use the Hector Guide to answer any questions I've had so far. Now, I'll continue to go through the other vignettes and experiment with Hector.

**Comment by bpbond** [comment]
Great!
